# Generated by Django 2.2 on 2019-04-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'sobre mi', 'verbose_name_plural': 'sobre mi'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Experiencia', 'verbose_name_plural': 'Experiencias'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AlterModelOptions(
            name='type_skill',
            options={'verbose_name': 'Tipo de Habilidad', 'verbose_name_plural': 'Tipos de Habilidades'},
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título'),
        ),
    ]
