# Generated by Django 2.2 on 2019-04-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190406_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nivel'),
        ),
    ]
