# Generated by Django 2.2 on 2019-04-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190406_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['type_skill'], 'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades'},
        ),
    ]
