# Generated by Django 2.2 on 2019-04-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190407_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['type_skill', 'level'], 'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades'},
        ),
    ]
