# Generated by Django 2.2 on 2019-04-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190407_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['end_date'], 'verbose_name': 'Experiencia', 'verbose_name_plural': 'Experiencias'},
        ),
    ]
